# Base configs
baseurl: "https://yellowprawn.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Damien Fung"
subtitle: "Street Photography and more!"
author: "Damien Fung"
header:
 title: "Photography"
 subtitle: "by Damien Fung"
footer:
 name: "Hi! I'm Damien!"
 bio: "I'm a 2nd year Statistics major at UBC who does photography in his free time!"
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a>"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/damien.fung.79"
  instagram: "https://www.instagram.com/damien.fotography"
  linkedin: "https://in.linkedin.com/in/damiien-fung"
  github: "https://www.github.com/yellowprawn"
